name: Markdown to PDF
on:
  push:
    branches: [ main ]
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir output
      - uses: docker://ghcr.io/44smkn/pandoc/ja:0.1.1
        with:
          args: README.md -s -o readme.pdf --pdf-engine=wkhtmltopdf
      - uses: actions/upload-artifact@main
        with:
          name: curriculum-vitae
          path: output/markdown.pdf
